services:
  - type: web
    name: yolo-damage-api
    runtime: docker
    plan: standard
    healthCheckPath: /health
    envVars:
      - key: API_KEY_DEMO
        scope: run
        value: demo-key-12345
    dockerfilePath: ./Dockerfile
    autoDeploy: true
